### ISSUE TITLE
[1.12.1][1.12.2-6.337] Crash on mounting ship, "java.lang.Boolean cannot be cast to java.lang.Byte"

### ISSUE THREAD

**Issue by DanNetwalker** [darkevilmac/archimedes-ships-plus#192]
Premises: a player puts some baloon blocks, a passenger seat and a helm. Crashes on "mount ship"

Modpack used: https://minecraft.curseforge.com/projects/redblockers-adventure-reforged/ - 2017-1.12.1-v1.2 version 
Minecraft Version: 1.12.1
Java Version: 1.8.0_25, Oracle Corporation
Forge version: 14.22.1.2485

java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Byte
	at com.elytradev.davincisvessels.common.entity.ShipCapabilities.canMove(ShipCapabilities.java:173)
	at com.elytradev.davincisvessels.common.entity.EntityShip.handleControl(EntityShip.java:263)
	at com.elytradev.movingworld.common.entity.EntityMovingWorld.handleServerUpdate(EntityMovingWorld.java:427)
	at com.elytradev.davincisvessels.common.entity.EntityShip.handleServerUpdate(EntityShip.java:391)
	at com.elytradev.movingworld.common.entity.EntityMovingWorld.func_70071_h_(EntityMovingWorld.java:360)
	at net.minecraft.world.World.func_72866_a(World.java:1984)
	at net.minecraft.world.World.func_72870_g(World.java:1946)
	at net.minecraft.world.World.func_72939_s(World.java:1754)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Complete crash log: https://pastebin.com/9SKiidr9

**Comment by Nianor** [comment]
So what's the deal with this? I'm getting the same error on a server now. Was this ever resolved?

**Comment by CMEmerson** [comment]
I am still seeing this crash
