### ISSUE TITLE
Vanishing Blocks Upon Ship Mount

### ISSUE THREAD

**Issue by Hypocrita20XX** [darkevilmac/archimedes-ships-plus#30]
Hello and good morning!

I ran into an issue where when I mount a ship, the helm vanishes, along with a good portion of the balloons and a few other assorted blocks.
![2015-07-02_06 11 23](https://cloud.githubusercontent.com/assets/13149236/8474837/333b43c0-2081-11e5-8d34-ea5e22c4fa53.png)

After looking in the log, the most relevant information I could find is the following.

[05:47:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[05:47:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.thecodewarrior.catwalk.BlockCatwalk.func_149749_a(BlockCatwalk.java:176)
[05:47:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:600)
[05:47:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.World.func_147465_d(World.java:451)
[05:47:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at darkevilmac.movingworld.chunk.AssembleResult.getEntity(AssembleResult.java:113)
[05:47:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at darkevilmac.movingworld.tile.TileMovingWorldMarkingBlock.mountMovingWorld(TileMovingWorldMarkingBlock.java:125)
[05:47:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at darkevilmac.archimedes.network.ClientHelmActionMessage.handleServerSide(ClientHelmActionMessage.java:54)
[05:47:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at darkevilmac.archimedes.network.ArchimedesShipsPacketHandler.channelRead0(ArchimedesShipsPacketHandler.java:28)
[05:47:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at darkevilmac.archimedes.network.ArchimedesShipsPacketHandler.channelRead0(ArchimedesShipsPacketHandler.java:15)
[05:47:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
[05:47:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[05:47:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[05:47:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[05:47:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
[05:47:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[05:47:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[05:47:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
[05:47:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
[05:47:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77)
[05:47:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[05:47:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
[05:47:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
[05:47:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[05:47:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
[05:47:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[05:47:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

I feel as though I may have added incorrect blocks, but nevertheless, I figured it best to let you in on this just in case it is something to be concerned with.

**Comment by darkevilmac** [comment]
Odd, so you don't crash but a large portion of the ship goes away... I'm noticing a method in the catwalk block that's throwing an error, could you try making a ship without the catwalks and see if that works?

**Comment by Hypocrita20XX** [comment]
No, I had that earlier. =-)
I didn't investigate that, however, for some reason. 

Anyways, the catwalk block error is odd, at least to me, due to it not actually being attached to the ship. I had a shore buffer decoupling that from the ship, only using those to get to it.
After rebuilding using only vanilla and Archimedes' blocks, I can mount just fine. Perhaps it was still counting that as being attached, or some other blocks I used before where incorrect and it didn't like that.

Thanks for your time!

**Comment by darkevilmac** [comment]
ISSUE MOVED: https://github.com/darkevilmac/MovingWorld/issues/7
