### ISSUE TITLE
1.8 large ships causing game to crash

### ISSUE THREAD

**Issue by br60066** [darkevilmac/archimedes-ships-plus#37]
Hello. I am having problems with large ships crashing minecraft when I mount them. Smaller ships (300ish or smaller) work fine. I am using 1.8 alpha of archimedesshipsplus and I have Moving world installed. I have put the crash report bellow.

Thanks

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MovingWorldCoreMod (movingworld-1.8-ALPHA-3.1-HFX.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 18/07/15 21:53
Description: Ticking entity

java.lang.StackOverflowError: Ticking entity
	at com.google.common.collect.HashBiMap.hash(HashBiMap.java:173)
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:224)
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:215)
	at darkevilmac.movingworld.common.util.LocatedBlockList.add(LocatedBlockList.java:26)
	at darkevilmac.movingworld.common.util.FloodFiller.fillCoord(FloodFiller.java:63)
	at darkevilmac.movingworld.common.util.FloodFiller.fillCoord(FloodFiller.java:66)
	at darkevilmac.movingworld.common.util.FloodFiller.fillCoord(FloodFiller.java:65)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.google.common.collect.HashBiMap.hash(HashBiMap.java:173)
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:224)
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:215)
	at darkevilmac.movingworld.common.util.LocatedBlockList.add(LocatedBlockList.java:26)
	at darkevilmac.movingworld.common.util.FloodFiller.fillCoord(FloodFiller.java:63)
	at darkevilmac.movingworld.common.util.FloodFiller.fillCoord(FloodFiller.java:66)
	at darkevilmac.movingworld.common.util.FloodFiller.fillCoord(FloodFiller.java:65)

-- Entity being ticked --
Details:
	Entity Type: ArchimedesShipsPlus.shipmod (darkevilmac.archimedes.common.entity.EntityShip)
	Entity ID: 20137
	Entity Name: entity.ArchimedesShipsPlus.shipmod.name
	Entity's Exact location: 152.00, 77.00, 319.50
	Entity's Block location: 152.00,77.00,319.00 - World: (152,77,319), Chunk: (at 8,4,15 in 9,19; contains blocks 144,0,304 to 159,255,319), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Rider: EntityPlayerMP['br60066'/884, l='archamedes test', x=131.50, y=84.15, z=319.50]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1684)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:571)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:704)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:164)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
	at java.lang.Thread.run(Thread.java:745)

-- Affected level --
Details:
	Level name: archamedes test
	All players: 1 total; [EntityPlayerMP['br60066'/884, l='archamedes test', x=131.50, y=84.15, z=319.50]]
	Chunk stats: ServerChunkCache: 1870 Drop: 0
	Level seed: -822576103146473031
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: 103.00,64.00,265.00 - World: (103,64,265), Chunk: (at 7,4,9 in 6,16; contains blocks 96,0,256 to 111,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3152 game time, 3152 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 74456 (now: false), thunder time: 120513 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 266494936 bytes (254 MB) / 1043341312 bytes (995 MB) up to 5355339776 bytes (5107 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -Xmx5120M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1450 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1450.jar) 
	UCHIJAAAA	Forge{11.14.3.1450} [Minecraft Forge] (forge-1.8-11.14.3.1450.jar) 
	UCHIJAAAA	darkevilmac.movingworld.common.asm.coremod{} [MovingWorld CORE] (minecraft.jar) 
	UCHIJAAAA	MovingWorld{1.8-ALPHA-3.1-HFX} [Moving World] (movingworld-1.8-ALPHA-3.1-HFX.jar) 
	UCHIJAAAA	ArchimedesShipsPlus{1.8-ALPHA-3.2} [Archimedes' Ships Plus] (archimedesshipsplus-1.8-ALPHA-3.2.jar) 
	Loaded coremods (and transformers): 
MovingWorldCoreMod (movingworld-1.8-ALPHA-3.1-HFX.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['br60066'/884, l='archamedes test', x=131.50, y=84.15, z=319.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by darkevilmac** [comment]
Read the error more carefully, as you can see it was huge. Note the lack of any real reference to archimedes ships plus, it's all related to MovingWorld. I'll be opening another issue in movingworld momentarily.
