### ISSUE TITLE
I have a problem (1.7.10)

### ISSUE THREAD

**Issue by godgoo** [darkevilmac/archimedes-ships-plus#64]
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 08.01.16 22:17
Description: Unexpected error

java.lang.IndexOutOfBoundsException: Index: 5, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at net.minecraft.inventory.Container.func_75139_a(SourceFile:104)
	at net.minecraft.inventory.Container.func_75141_a(SourceFile:385)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147266_a(NetHandlerPlayClient.java:1027)
	at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:27)
	at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by DrasticDemise** [comment]
I and multiple people have recieved this crash on the same server when accessing the ships helm, however different people can access the same helm and not crash at all. And the problem simply seems to go away and then come back randomly to affect a different person trying to access any ships.

**Comment by darkevilmac** [comment]
Please modify your issue to be in line with the Contributing.MD, also this has been addressed tons of times fairly sure I've already done a fix on the repo, it's just not in the builds that are posted at the moment.
