### ISSUE TITLE
Issue with Rendering Ship with ModBlocks 

### ISSUE THREAD

**Issue by PacWhite** [darkevilmac/archimedes-ships-plus#95]
I use AS+ under 1.7.10. 

If i compile a ship with ComputeCraft Mods the Display of my Laptop flicker in endless mode in Miecraft, the world is destructet and not playable anymore. 

This Error come up if game crash..
`[09:33:23] [Client thread/ERROR]: ########## GL ERROR ##########
[09:33:23] [Client thread/ERROR]: @ Post render
[09:33:23] [Client thread/ERROR]: 1282: Invalid operation
[09:33:23] [Client thread/ERROR]: A mobile chunk render error has occured
java.lang.NullPointerException
    at dan200.computercraft.shared.computer.blocks.TileComputerBase.getFamily(TileComputerBase.java:412) ~[TileComputerBase.class:?]
    at dan200.computercraft.shared.computer.blocks.TileComputer.getTexture(TileComputer.java:150) ~[TileComputer.class:?]
    at dan200.computercraft.shared.common.BlockGeneric.func_149673_e(BlockGeneric.java:334) ~[BlockGeneric.class:?]
    at net.minecraft.client.renderer.RenderBlocks.func_147793_a(RenderBlocks.java:8227) ~[blm.class:?]
    at net.minecraft.client.renderer.RenderBlocks.func_147751_a(RenderBlocks.java:4549) ~[blm.class:?]
    at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4247) ~[blm.class:?]
    at dan200.computercraft.client.proxy.ComputerCraftProxyClient$ComputerBlockRenderingHandler.renderWorldBlock(ComputerCraftProxyClient.java:295) ~[ComputerCraftProxyClient$ComputerBlockRenderingHandler.class:?]
    at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118) ~[RenderingRegistry.class:?]
    at FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53) ~[FMLRenderAccessLibrary.class:?]
    at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:296) ~[blm.class:?]
    at darkevilmac.movingworld.client.render.MobileChunkRenderer.updateRender(MobileChunkRenderer.java:181) ~[MobileChunkRenderer.class:?]
    at darkevilmac.movingworld.client.render.MobileChunkRenderer.render(MobileChunkRenderer.java:80) [MobileChunkRenderer.class:?]
    at darkevilmac.movingworld.client.render.RenderMovingWorld.renderVehicle(RenderMovingWorld.java:37) [RenderMovingWorld.class:?]
    at darkevilmac.movingworld.client.render.RenderMovingWorld.func_76986_a(RenderMovingWorld.java:45) [RenderMovingWorld.class:?]
    at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293) [bnn.class:?]
    at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:271) [bnn.class:?]
    at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:244) [bnn.class:?]
    at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:471) [bma.class:?]
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224) [blt.class:?]
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011) [blt.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
[09:33:23] [Client thread/ERROR]: ########## GL ERROR ##########
[09:33:23] [Client thread/ERROR]: @ Post render
[09:33:23] [Client thread/ERROR]: 1282: Invalid operation
[09:33:23] [MCEF-Shutdown/INFO]: Shutting down JCEF...
[09:33:23] [Client thread/INFO]: Stopping!
[09:33:23] [Client thread/INFO]: World unloaded; killing web views...`

**Comment by PacWhite** [comment]
**It is possible to made a Fallback that simple abort the Shiprendering with a Message like "You use Microblocks on the ship - please do it not."**

**Comment by darkevilmac** [comment]
1.7.10 is no longer supported.

**Comment by PacWhite** [comment]
Is this fixed in newer versions?
